[package]
name = "bake-releases-project"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
bake = "0.17.0"
bake-agent-context = { version = "0.1.1" }
bake_cargo = { package = "bake-cargo", version = "0.2.4" }
bake_license = { package = "bake-license", version = "0.1.1" }
bake_releases = { package = "bake-releases", version = "0.2.2", path = ".." }
