[package]
name = "bake-releases-project"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
bake = { package = "socketry-bake", version = "0.2.1" }
bake-agent-context = { version = "0.1.0" }
bake_cargo = { package = "bake-cargo", version = "0.2.0" }
bake_license = { package = "bake-license", version = "0.1.0" }
bake_releases = { package = "bake-releases", version = "0.2.0" }
